version: '3.8'
services:

  pihole:
    image: pihole/pihole:latest
    container_name: pihole_stack
    restart: unless-stopped
    environment:
      TZ: "Europe/Warsaw"
      WEBPASSWORD: "admin"
      DNS1: "1.1.1.1"
      DNS2: "1.0.0.1"
    network_mode: "host"
    volumes:
      - pihole_etc:/etc/pihole
      - pihole_dnsmasq:/etc/dnsmasq.d
      
  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    volumes:
      - influxdb2:/var/lib/influxdb2
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: "admin"
      DOCKER_INFLUXDB_INIT_PASSWORD: "changeme"
      DOCKER_INFLUXDB_INIT_ORG: "my-org"
      DOCKER_INFLUXDB_INIT_BUCKET: "network_metrics"
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: "my-super-secret-token"
      DOCKER_INFLUXDB_INIT_BUCKET_RETENTION: 336h
      
  grafana:
    image: 'grafana/grafana-oss:latest'
    container_name: grafana
    restart: unless-stopped
    depends_on:
      - influxdb
    ports:
      - '3000:3000'
    volumes:
      - 'grafana_data:/var/lib/grafana'
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin123
      
  pinger:
    build:
      context: ./pinger
      dockerfile: Dockerfile
    container_name: pinger
    restart: unless-stopped
    depends_on:
      - influxdb
    environment:
      INFLUX_URL: http://influxdb:8086
      INFLUX_TOKEN: my-super-secret-token
      INFLUX_ORG: my-org
      INFLUX_BUCKET: network_metrics
      PING_TARGET: 1.1.1.1
      PING_INTERVAL: 30
      
volumes:
  portainer_data: null
  pihole_etc: null
  pihole_dnsmasq: null
  influxdb2: null
  grafana_data: null
